# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=150)),
                ('num_pages', models.PositiveIntegerField()),
                ('num_copies', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(null=True)),
                ('books_lent', models.ManyToManyField(blank=True, to='book_shelf.Book')),
                ('privileges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shelf.Privileges')),
            ],
        ),
    ]
